misc
ferncabrera/open_ims pull request #237
Opened 2024-06-16 15:14 UTC by ferncabrera

Includes:

GlobalBanner Timing patches:
- Basically I made sure that we are syncing the timing that the loading bar crawls with the timing that the react component shows by using the SCSS variable and some regex. Otherwise we should show the Banner component infinitely and hide the loading bar. So now the "infinite" attribute on the globalBannerState is just a boolean, set it to TRUE if you want the banner to show infinitely, otherwise it will default to the SCSS variable duration.

2024-06-18 06:22 UTC, Polsander commented on microservices/client/src/components/banners/GlobalBanner.tsx
> +    let secondsToDisplayAlert = styles.alertDisplaySeconds.match(regex);
Yeah I definitely noticed timing errors before. Good catch and implementation here!

2024-06-18 06:27 UTC, Polsander requested changes
Amazing!
Good use of the variables.scss file! Did not think of using it at the time for our first implementation of the global banner.

To address your comment. On "heavy" redirects we do want to reset the banner state, since we do not want to show an error from one page to stay on a different screen... to some extent.

We may want to keep error screens where possible for asynchronous changes. For example, future uploads or notification handling should show across multiple screens until the user dismisses the banner, especially if there is an error. See if you'd like to implement this, if not for now then I am fine with any changes you've made so far merging to main.

2024-06-24 16:16 UTC, Polsander approved these changes
Approved and ready for merge if my comments were addressed :)

2024-08-11 02:14 UTC, ferncabrera commented
This was merged into invoices crud - I watched it happen.

2024-08-11 02:14 UTC, closed without merging