282 products page
ferncabrera/open_ims pull request #301
Opened 2024-08-25 16:31 UTC by ferncabrera

2024-08-26 09:25 UTC, ferncabrera commented
Please let me know what you think and merge if it is OK!
**Updates**
- Running dev now should not start any unnecessary processes for you (prometheus, loki etc)!
-           I also added the SCSS mount path so now .SCSS updates dont trigger container restarts and will hot-reload the changes like they should have been...... lol this is going to save me so much time and stop me from using inline styles lol. I sent you more about this on discord
- We now have a mainController and hook to go along with it for a central place to manage our entity state easier in the future 
- We now use the useMatches() hook built into react-router to manage our crumbs and such. 
- External redirects and all now work as well, although that just means they are allowed and set our entity state properly lol


My hope for these changes is that we can piggy back off of this logic in the future to implement stores and whatnot easier. Also we now have a completely reactive main container. 

Still todo would be logic for the default controller and operation controller to validate the entity state paths and redirect if the URL is faulty or does not exist, right now, the behaviour is weird and will not redirect but flash an error screen since we do not handle this explicitly like before. 

This new logic should break nothing AFAIK and be backwards compatible with any old routes I should have missed.

2024-08-26 10:19 UTC, Polsander requested changes
![image](https://github.com/user-attachments/assets/0ef1662f-54bd-48c5-b8af-d0014913e4b4)

Really cool to see that the breadcrumbs are dynamic.
Just a couple of stylistic things I would like to point out.

- Can we have the `/` between the pill boxes rather than inside them? It would look a lot nicer. Right now there also seems to be some awkward spacing where the entire text seems off to the right of these pill boxes.
- `update 3` gives almost no information on what it is we are editing. Can we have it track based on some sort of entity that if it's a sales or invoice, it would therefore say `update invoice 3` ?

2024-08-26 10:23 UTC, Polsander requested changes
Does this PR maintain state history?

I go through this process:
Select sales invoice 3 > edit sales invoice 3 > click cancel on the form> I get redirected to the dashboard ??? 
I should at the very least be taken back to the invoices table page. Bonus points if it preserves the same table state. (You can temporarily store the meta data and pass it in  when we cancel or revert back to previous pages)

For example, when you change state path, you grab the current/previous state path along with any table search queries, page index, and table size parameters. When the user cancels or reverts the state, we pop the previous path which we redirect to and then you reinitialize the meta data you saved to get back to the previous table which the user was at.

Edit: I see we can consider stores later. So I would be careful with cancel buttons sending the user back to the dashboard. Very rarely should anything redirect back to dashboard.

2024-08-26 10:54 UTC, Polsander requested changes
Some of the things I was nit picky on.
Overall really good job and I was happy to see you left a lot of good comments and examples as well as future improvement locations.

Address issues or reply to my comments, if they all get resolved you have my approval :)

2024-08-26 10:54 UTC, Polsander commented on microservices/client/src/components/table/TableLink.tsx
> +            to="#"
<Link> is also stateful I believe. Quickly explain why we are having to='#' ?

2024-08-26 10:54 UTC, Polsander commented on microservices/client/src/containers/main/useMainNavigation.tsx
Make a separate custom hooks folder. This should not be in containers.

2024-08-26 10:54 UTC, Polsander commented on microservices/client/src/containers/operationController/DefaultController.tsx
> +    //? Can also validate here whether route exists
That and we will also need a proper error screen since any url can be input now.

2024-08-26 10:54 UTC, Polsander commented on microservices/client/src/containers/operationController/DefaultController.tsx
> +    //? Can also validate here whether route exists
Not related to PR but would be great if you could open a ticket for that and then resolve this discussion.

2024-08-26 10:54 UTC, Polsander commented on microservices/client/src/containers/operationController/OperationController.tsx
> +    switch (action) {
Potential risk for bug, but as soon as one case gets run, all subsequent cases below it will also run. The return statement protects it from this, but for extra security and bug prevention can you add a `break;` statement below each return? Provided that TS does not yell at you.

2024-08-26 10:54 UTC, Polsander commented on microservices/client/src/containers/operationController/RenderDefault.tsx
> +    switch (category) {
Might be unnecessary because of the return statement, but again, might want to consider adding `break;` up to you.

2024-08-26 10:54 UTC, Polsander commented on microservices/client/src/styles/general/colors.scss
> +$button-border-grey: $light-grey;
Why not just stick with light-grey? You're just assigning a color name to a different color here.

2024-08-26 16:35 UTC, ferncabrera commented on microservices/client/src/containers/main/useMainNavigation.tsx
Done, I added it to the hooks/ folder. I didn't at first since it really should only be used for the main container and we didnt even need to abstract it but I guess it makes sense.

2024-08-26 16:35 UTC, ferncabrera commented on microservices/client/src/containers/operationController/DefaultController.tsx
> +    //? Can also validate here whether route exists
Sure, will do that

2024-08-26 16:37 UTC, ferncabrera commented on microservices/client/src/containers/operationController/OperationController.tsx
> +    switch (action) {
Good idea, but adding it below actually just shows that the break; would never execute since we already return above. So no need :D

2024-08-26 16:39 UTC, ferncabrera commented on microservices/client/src/styles/general/colors.scss
> +$button-border-grey: $light-grey;
I think I was trying to see if we  could do this for more descriptive names in the future, I say we just keep this one since I thikn I might start setting some other names similar to this but for general stlying across the app.

2024-08-26 16:42 UTC, ferncabrera commented
"Edit: I see we can consider stores later. So I would be careful with cancel buttons sending the user back to the dashboard. Very rarely should anything redirect back to dashboard."

Regarding this, my PR does not change the logic used for the redirects or anything, the cancel buttons still point to where they have before I assume. As we start working on our state/redirect/storage more (which is not part of this ticket anymore) we will most likely start managing where/how we redirect a lot more but thats for another day......

2024-08-27 03:44 UTC, ferncabrera commented
please merge it in if it look OK to you!

2024-08-27 07:01 UTC, Polsander requested changes

2024-08-28 06:54 UTC, Polsander approved these changes
Beautiful. Approved

2024-08-28 06:54 UTC, merged