282 products page
ferncabrera/open_ims pull request #330
Opened 2024-09-13 14:26 UTC by ferncabrera

Bunch of stuff here that is on my local but can go in. Fixes misc issues with validation etc etc.

2024-09-13 18:11 UTC, Polsander commented on microservices/client/src/containers/invoices/EditCreateInvoice.tsx
> +                setBanner({ message: response.message, variant: 'danger', debugInfo: response?.debugInfo ? response?.debugInfo : ""})
Are we adding that to all banners? Or just a few?

If so that is pretty lengthy, why not just add it in the interface definition so we don't have to check like this. (See how I made it mandatory for a response to always provide a message so we don't check if `response.message` exists)

2024-09-13 18:14 UTC, Polsander commented on microservices/client/src/containers/purchaseOrders/TableSchema.tsx
> +        const day = String(date.getUTCDate()).padStart(2, "0");
Outdated code. We have functions that do this for us. I will try and implement them.

2024-09-13 18:54 UTC, Polsander requested changes

2024-09-13 18:54 UTC, Polsander commented on microservices/client/src/containers/purchaseOrders/TableSchema.tsx
>          const date = new Date(ISODate);
```suggestion
```

2024-09-13 18:54 UTC, Polsander commented on microservices/client/src/containers/purchaseOrders/TableSchema.tsx
>          dateString = `${day}/${month}/${year}`
```suggestion
       dateString = convertDateISO(ISODate, 0)
```

2024-09-13 18:54 UTC, Polsander commented on microservices/client/src/containers/products/ReadTableSchema.tsx
> +      const month = String(formatDate.getUTCMonth() + 1).padStart(2, "0"); // Months are zero-based, so add 1
Use the `convertDateISO` function here please. Parameters would be date and 0.

2024-09-13 18:54 UTC, Polsander commented on microservices/client/src/containers/customers/ReadTableSchema.tsx
> +      const month = String(formatDate.getUTCMonth() + 1).padStart(2, "0"); // Months are zero-based, so add 1
Use the convertDateISO function here. See other review comments I left for example.

2024-09-13 18:54 UTC, Polsander commented on microservices/client/src/components/table/CCGTable.tsx
> +  filters?: { label: string, type: string, id: number, active?: boolean }[];
What is the active here for?

2024-09-13 18:54 UTC, Polsander commented on microservices/client/src/containers/vendors/EditCreateVendor.tsx
> +      isOverallInvalid = true;
Why do we need isOverallInvalid? It seems redundant here. Everywhere it is set to true, the submitted form should not go forward.

2024-09-13 18:54 UTC, Polsander commented on microservices/client/src/containers/vendors/EditCreateVendor.tsx
> +    const requiredAddrArr = [
Are addresses mandatory now? 
If so, you need to provide it in the error object, and also need to provide a feedback message under the fields.

2024-09-13 18:54 UTC, Polsander commented on microservices/client/src/containers/vendors/EditCreateVendor.tsx
> +        setBanner({ message: res.message, variant: 'danger', debugInfo: res?.debugInfo });
If every banner will have a debug info, this needs to be added in the interface. Otherwise default to null.

2024-09-13 18:54 UTC, Polsander commented on microservices/client/src/globals.d.ts
> +interface IGeoCodeSeachTerms {
Why is this global? Is it going to be reused globally throughout the app?
Otherwise just keep this interface where you define GeoCodeSearchTerms

2024-09-13 18:58 UTC, Polsander commented
This was a Big PR with a lot of changes. It made it hard to track during my code review, with it being 23 files I had to view.
Let's keep PR's shorter in the future and link them to a specific issue.

Also I think we need to discuss big changes involving addresses. Traditionally, invoices do not require addresses in receipt or sale purchases.
If this is in regards to setting up geo location, and requiring addresses for that service, we need to discuss together how that is going to work. It will be more complicated than we think in terms of what we **should** do, and has less to do with just mapping addresses that are given.

2024-09-17 19:20 UTC, ferncabrera commented on microservices/client/src/components/table/CCGTable.tsx
> +  filters?: { label: string, type: string, id: number, active?: boolean }[];
Required for determining the state of our filters now for the tables

2024-09-17 19:23 UTC, ferncabrera commented on microservices/client/src/containers/invoices/EditCreateInvoice.tsx
> +                setBanner({ message: response.message, variant: 'danger', debugInfo: response?.debugInfo ? response?.debugInfo : ""})
Done

2024-09-17 19:24 UTC, ferncabrera commented on microservices/client/src/containers/products/ReadTableSchema.tsx
> +      const month = String(formatDate.getUTCMonth() + 1).padStart(2, "0"); // Months are zero-based, so add 1
Done

2024-09-17 19:33 UTC, ferncabrera commented on microservices/client/src/containers/vendors/EditCreateVendor.tsx
> +    const requiredAddrArr = [
We spoke about this. I will make sure to fix the address fields with the required alerting/properties after I make the required cahnges to the address fields in the database. For now this is just a POC and shows how we can use the current pattern to work around out issue of validating all fields

2024-09-17 19:34 UTC, ferncabrera commented on microservices/client/src/containers/vendors/EditCreateVendor.tsx
> +      isOverallInvalid = true;
Required because the validateFormOnSubmit function does not validate nested objects and so we need to extract and check each object seperately, and then use the flag to ensure we have checked all objects and they are all good. We will fix this moving forward again just a quick POC

2024-09-19 05:48 UTC, Polsander approved these changes

2024-09-21 03:27 UTC, merged