Backend authentication
ferncabrera/open_ims pull request #61
Opened 2023-08-12 20:39 UTC by Polsander

Registration creates user in the database.
Login verifies user email and password from database. Basic back-end error handling.
Cookie is created upon successful login.

---
Need a separate ticket for creating front-end loading state.
Redux for success global message banners (need reusable component as well)
Need more cases for error handling in the back-end and reflecting it to the front-end incase something goes wrong.

--- 
Ready to merge.
Please review all operations in Network tab and PGadmin. I will come home tonight, and if there are no questions I can merge it myself. (Or fernando/kelly/joseph can).

2023-08-12 22:48 UTC, ferncabrera requested changes
Let me know when you review my comments

2023-08-12 22:48 UTC, ferncabrera commented on microservices/server/index.ts
> +initializeDatabaseSchema().then(() => {
Checked this out on my local and confirmed my thoughts:

If initializeDatabaseSchema were to fail (which happens to me occasionally because the database service takes longer to start and is not available before server starts) then the server wouldn't start at all because we would be thrown into the catch. Simple workaround in DEV is to just make a file change and get it to reload but if for whatever reason in PROD this happens we would need to merge in a change to main or redeploy the service manually from local which I would like to try and avoid.

What I say we do for now is continue to use the janky API way to seed it, that way in DEV, if it fails, we just hit the api/server/seed thing. and in  PROD, if it fails, server still runs but we just instead manually hit the API route and it will re-seed/create the new tables.

I should be able to change this with our migration script pattern. The scripts would not be run in the server, but instead as a Kuberentes Job, but still looking into this. So for now I think it's safer to use the API way, what do you think?

2023-08-12 22:48 UTC, ferncabrera commented on microservices/server/kustomize/overlays/prod/.env
> +JWT_SECRET_KEY= "1mnxI7I$]>^lprZu-']Vm[Pj>(0NS>7;JoG?>m=@Ik9vxJDU5=~O{N!YDt$#M,n"
Let me know if you want me to show you how to do this in production yourself @Polsander, it takes no time at all, but we shouldn't deploy this into prod LOL. If you'd rather me do it lmk and ill manually create the secrete object and have them available to your container as these ENV vars before you merge it in. Just remove them from the PR tho

2023-08-12 22:48 UTC, ferncabrera commented on microservices/server/src/db/schema.ts
This file is a need, thanks for making this. But yeah lets have this hit from an api maybe LOL.

2023-08-12 22:48 UTC, ferncabrera commented on microservices/server/src/controllers/users.ts
> +    const userQuery = await query("SELECT * FROM user_table WHERE email = $1", [email]);
Hmmmmm, I thought that this was bad practice? Attacker could theoretically send a body with malicious SQL string in email field using postman (since this is an unauthorized route), bypassing client-side validation and then that is directly injected into our query.

I thought that we had to sort of pre-determine the string going into the query. I could be totally wrong but just playing devils advocate, let me know your thoughts

2023-08-13 01:28 UTC, JosephFanous requested changes
Fernando covered everything - looks good other than that.

2023-08-13 06:22 UTC, Polsander commented on microservices/server/index.ts
> +initializeDatabaseSchema().then(() => {
Didn't know Prod was susceptible to this problem as well...

Obviously it's not safe to have this happen. I can see if I can just call the asynchronous function without making any .then() statements for now. Will the migration script pattern find a fix for this, since it seems to be a different underlying issue.

2023-08-13 06:23 UTC, Polsander commented on microservices/server/kustomize/overlays/prod/.env
> +JWT_SECRET_KEY= "1mnxI7I$]>^lprZu-']Vm[Pj>(0NS>7;JoG?>m=@Ik9vxJDU5=~O{N!YDt$#M,n"
Busy with baseball this weekend. Maybe Sunday afternoon. I will remove them for now and send you the prod token code.

2023-08-13 06:25 UTC, Polsander commented on microservices/server/src/db/schema.ts
I will keep the file. 
Will run the async function without awaiting or handling any promises as the seed function.
(If that's what you intend on doing for now)

2023-08-13 06:35 UTC, Polsander commented on microservices/server/src/controllers/users.ts
> +    const userQuery = await query("SELECT * FROM user_table WHERE email = $1", [email]);
No, this is a parameterized way of sending data to an sql query.
This is bad practice:
 `const userQuery = await query("SELECT * FROM user_table WHERE email = ${email}"`;
Good practice:
`const userQuery = await query("SELECT * FROM user_table WHERE email = $1", [email]);`

I am not adding the **req.body** directly into the text string. If anyone were to send malicious data or scripts then that would be vulnerable to sql injection as that gets put directly into the string. Adding it as a parameter on the other hand makes postgres sanitize it before placing it into the query string. This whole good practice is known as "parametrization".
---
We also need back-end validations now that I think of it which could further improve security. A general function with a few regex cases will do. I can make a separate issue for this.

2023-08-13 07:01 UTC, Polsander commented on microservices/server/index.ts
> +initializeDatabaseSchema().then(() => {
Added InitializeDatabaseSchema to the seed function.

2023-08-13 07:36 UTC, Polsander commented
@ferncabrera Front-end tests are failing because docker environment variables don't seem to be setup properly I am guessing.

An error occurred: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Module.apiCall (/home/node/app/src/utilities/apiCall.ts:18:26)
    at Module.sendPostRequest (/home/node/app/src/utilities/apiHelpers.ts:35:31)
    at handleSignIn (/home/node/app/src/containers/auth/Login/index.tsx:107:26) {
  cause: Error: getaddrinfo ENOTFOUND undefined
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'undefined'
  }
}
url http://undefined/api/server/login

Our url is coming in undefined in our github actions.
Let me know if this is something you can fix or if you know the issue. Otherwise let's debug in our call tomorrow.

2023-08-13 13:24 UTC, ferncabrera commented
> @ferncabrera Front-end tests are failing because docker environment variables don't seem to be setup properly I am guessing.
> 
> An error occurred: TypeError: fetch failed at Object.fetch (node:internal/deps/undici/undici:11576:11) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Module.apiCall (/home/node/app/src/utilities/apiCall.ts:18:26) at Module.sendPostRequest (/home/node/app/src/utilities/apiHelpers.ts:35:31) at handleSignIn (/home/node/app/src/containers/auth/Login/index.tsx:107:26) { cause: Error: getaddrinfo ENOTFOUND undefined at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) { errno: -3008, code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'undefined' } } url http://undefined/api/server/login
> 
> Our url is coming in undefined in our github actions. Let me know if this is something you can fix or if you know the issue. Otherwise let's debug in our call tomorrow.

Yeah - you're right, forgot Skaffold uses Kubectl+Kustomize to create the environments at a k8s level, not anything that would be present on a regular Docker build. Let me see if I can find some time to fix this b4 the meeting but im still trying to work out our db operations in production so I can have something to show you all lol

2023-08-13 15:51 UTC, ferncabrera submitted a review, later dismissed
LGTM

2023-08-13 15:58 UTC, JosephFanous submitted a review, later dismissed
: - )

2023-08-13 17:13 UTC, Polsander commented
I will merge this PR tonight after I come home from baseball. Thanks everyone.

2023-08-14 23:50 UTC, merged