Joseph branch
ferncabrera/open_ims pull request #86
Opened 2023-08-22 16:44 UTC by JosephFanous

Completed all the forgot password flow; added a new page to reset the password BUT could not get the image as the background so I styled it as well as I can for now until the next update. All functionalities work including:

- Backend server calls
- Front end
- Validation that the new password meets the requirements
- Passwords match
- New password is not the same as the old password
- Added a new PATCH HTTP method as I am updating the user's password with a PATCH method
- Using PATCH rather than PUT because it is a partial update and not an entire table update
- Used Brevo to send an email containing a reset password link, which expires in 10 minutes
- Brevo has analytics which we will need to look into in the future
- Email template is created locally, so we can update however we would like - right now I have it barebones (look below)
![image](https://github.com/ferncabrera/open_ims/assets/43254313/07fd93fd-ac80-45ff-b470-6b787ab50893)

- If you want to test this out just let me know and I'll send you a new Brevo API key, or you can also make an account to generate keys with

I might have forgotten to add some points above. 
Also, @kellygibson please take a look at the UI and let me know if anything should change, will add the image once I connect with @Polsander to see how it is done.
And of course, look at the code and let me know if anything should change.

2023-08-22 17:16 UTC, Polsander requested changes
Make requested changes. As for general comments, you can provide a fix or clarification. If all my queries are answered I will give an approval :)

Good work btw. This was a big ticket!

2023-08-22 17:16 UTC, Polsander commented on microservices/server/src/controllers/forgot_pass.ts
> +<html>
Are we able to define emailTemplates on Brevo itself? I have no problem defining it here, but if we have an option of using custom templates on the site, Kelly can make direct edits there.

Or we have a second option, where Kelly can mock up a figma and you can define the template here if we need more customizability. I'd quickly talk with her regarding this. @kellygibson

2023-08-22 17:16 UTC, Polsander commented on microservices/server/src/controllers/forgot_pass.ts
> +    { email: "joseph_fanous@hotmail.com", name: "Joseph Fanous" },
Shouldn't this be sending it to the user who is resetting their password? Why are we hard-coding this?

2023-08-22 17:16 UTC, Polsander commented on microservices/server/src/controllers/forgot_pass.ts
> +    email: "joseph.fanous.01@gmail.com",
@ferncabrera What company email did Austin provide us which we can use here?

2023-08-22 17:16 UTC, Polsander commented on microservices/client/src/routes.tsx
> +    {
I haven't tested in my environment, and probably won't be able to until later tonight.
Should this route be accessed by token which we verify? ex. `localhost/<tokenUUID>/forgot_pass`

This will ensure that no one can access this route without a valid link.
It should also identify which use (by email) is trying to reset their password.

2023-08-22 17:16 UTC, Polsander commented on image-1.png
What are these BIN images? Why are we adding them to repo? There are at least 5 in this PR right now.

2023-08-22 17:51 UTC, JosephFanous commented on image-1.png
The 4/5 are for the readme which helps describe the steps to add a credential key, and 1/5 is the background from Figma (which is not yet implemented, just sitting in the assets folder)

2023-08-22 18:01 UTC, JosephFanous commented on microservices/server/src/controllers/forgot_pass.ts
> +import customError from "../utils/customeError";
done

2023-08-22 18:02 UTC, JosephFanous commented on microservices/client/src/utilities/apiCall.ts
> +    console.log("url", props.url);
done

2023-08-22 18:02 UTC, JosephFanous commented on microservices/client/src/utilities/apiCall.ts
> +      console.log("responseWithStatus", resposneWithStatus);
done

2023-08-22 18:02 UTC, JosephFanous commented on microservices/client/src/utilities/apiCall.ts
> +  console.log("props", props);
done

2023-08-22 18:06 UTC, JosephFanous commented on microservices/server/src/controllers/forgot_pass.ts
> +<html>
I will reach out to @kellygibson to get a template and try to mock it.

2023-08-22 18:09 UTC, JosephFanous commented on microservices/server/src/controllers/forgot_pass.ts
> +    { email: "joseph_fanous@hotmail.com", name: "Joseph Fanous" },
You're right, this was used for testing. Changed it to the user's email and name

2023-08-22 18:10 UTC, JosephFanous commented on microservices/server/src/controllers/forgot_pass.ts
> +    email: "joseph.fanous.01@gmail.com",
I also changed it to the email Austin gave Fernando which was ccg.ca.inquiries@gmail.com

2023-08-22 18:16 UTC, JosephFanous commented on microservices/client/src/routes.tsx
> +    {
As of right now, anyone can hit this route but updating their password won't work as the jwt token gets invalidated after it is used once to update that user's password.

2023-08-22 23:40 UTC, JosephFanous commented
I just made another PR which handles jwt revocation. It works by invoking a function which adds a token to a set once it has been used, It also checks if the token has been added to the revoked tokens set prior to updating the password.
I am currently working on an update which will make it more sustainable in the long run, it will run a cleanup task every 10 minutes and delete tokens that have been in the set for > 10 minutes since our tokens have an expiration date of 10 minutes. This is better for the long run as it will help keep the set size manageable and prevents it from growing indefinitely with expired tokens. However, this will not be a good choice if we ever decide to run on multiple servers as some issues might arise, like inconsistent cleanup or potential redundancy. Ask me more on Discord if you want to know - too much typing here lol

2023-08-23 01:35 UTC, Polsander commented on microservices/client/src/routes.tsx
> +    {
@JosephFanous Could you please make an enhancement issue/ticket for protecting this route then? This is fine for now, but once we figure out how to protect routes in our front-end we should also probably protect this one since it would be a bad user experience for people who did not get the reset link to be able to access this.

Also not sure how the system would then be able to understand which user is resetting their password if 2 people access the page at the same time. Would be easier to discuss in call :)

2023-08-23 01:37 UTC, Polsander commented on image-1.png
Maybe my github is just acting weird, but it shows each individual jpeg file at the root level on its own. If you could just find a good spot to place them, (maybe make a readme assets folder?) I would be happy to resolve this issue here.

2023-08-23 01:38 UTC, Polsander commented
Re-request me to review when you're ready.

2023-08-23 02:26 UTC, kellygibson requested changes
Hey Joseph, looks great so far! Here are a few notes to keep in mind:

- I think some of the fonts used aren't quite right, if you ever want to check a font or colour I've used in the figma files I've got them all listed in the design system screens 
<img width="862" alt="Screenshot 2023-08-22 at 10 03 57 PM" src="https://github.com/ferncabrera/open_ims/assets/139164128/868f0379-d6bf-41cc-b3d9-99ce4171f6fb">

-  the text: "Your new password must be different from your previously used passwords."  doesn't look properly aligned, looks too far to the left 

- there should be an equal amount of space between this text to the first password field, and the bottom of the second field to the button

<img width="470" alt="Screenshot 2023-08-22 at 10 17 24 PM" src="https://github.com/ferncabrera/open_ims/assets/139164128/8eaa4389-9d8c-4069-bc67-d71754ec934c">

-  border radius too high should only be 10px

2023-08-23 03:36 UTC, Polsander submitted a review, later dismissed
Looks 🔥🔥
Wait for the .env changes from Fernando. And if Kelly's requests are addressed, you got my approval.

2023-08-23 03:38 UTC, Polsander approved these changes

2023-09-04 19:00 UTC, ferncabrera commented
waiting on wednesday push to review 😃

2023-09-09 17:43 UTC, JosephFanous commented
Spoke with Fernando but I can't currently work/update on this PR the request changes from Kelly. Since they are only style change, we will merge this PR with main and I will push directly into main once I can (The changes are all done but are on my local desktop which I can't use atm). For any questions just let me know!

2023-09-23 17:27 UTC, kellygibson commented
<img width="1440" alt="Screenshot 2023-09-23 at 1 23 21 PM" src="https://github.com/ferncabrera/open_ims/assets/139164128/3d49a51a-4acf-4a8b-b483-11308643f506">
Image looks very zoomed in and background colour of modal looks blue (should be white). Please adjust these two, other than that looks great!

2023-09-23 17:45 UTC, ferncabrera submitted a review, later dismissed
Just remember that we need to manually update the prod-postgres-credentials secret on the do-server.

You can switch k8s contexts on local todo this from your machine terminal as long as you've authenticated your machine.

Let me know if you want to hop on a a quick <5min call for this. Great work and thanks Joseph excited to try this out :D

2023-09-23 18:34 UTC, Polsander approved these changes
Approving.
One thing I want to say is that I noticed that in the css you added a body. Let's try to avoid this in the future (this is ok for now since this page is its own entity).

We have global styles that set our font, spacing, and general container styling that already defines body and html. All that is needed is to just add the appropriate open-ims-styling wrapper to whichever screen/component you are working on. This is more for a future reference.

Also we need to look into why my reviews keep getting revoked every time there is a new push. This is probably a default setting on github's side.

2023-09-23 22:44 UTC, merged

2023-09-23 22:46 UTC, JosephFanous commented
merged : )